# Generated by Django 5.0.4 on 2024-06-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_squashed_0013_alter_shopproduct_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='admin_comment',
            field=models.TextField(blank=True, max_length=300, verbose_name='Комментарий админа'),
        ),
        migrations.AlterField(
            model_name='shopproductkey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
